Update these scripts and enhance

diff --git a/bin/extract b/bin/extract
--- a/bin/extract
+++ b/bin/extract
@@ -10,33 +10,30 @@
 #
 ######################################################################
 
-. "$DOTPATH"/etc/lib/vital.sh
+if [ -z "$1" ]; then
+    echo "too few argument" 1>&2
+    exit 1
+fi
 
-extract() {
-    if [ -z "$1" ]; then
-        die "too few argument"
-        return 1
-    fi
+if [ -f "$1" ]; then
+    echo "$1: invalid file" 1>&2
+    exit 1
+fi
 
-    if [ -f "$1" ] ; then
-        case "$1" in
-            *.tar.bz2) tar xvjf   "$1" ;;
-            *.tar.gz)  tar xvzf   "$1" ;;
-            *.bz2)     bunzip2    "$1" ;;
-            *.rar)     unrar x    "$1" ;;
-            *.gz)      gunzip     "$1" ;;
-            *.tar)     tar xvf    "$1" ;;
-            *.tbz2)    tar xvjf   "$1" ;;
-            *.tgz)     tar xvzf   "$1" ;;
-            *.zip)     unzip      "$1" ;;
-            *.Z)       uncompress "$1" ;;
-            *.7z)      7z x       "$1" ;;
-            *)         echo "'$1' cannot be extracted via >extract<" ;;
-        esac
-    else
-        echo "'$1' is not a valid file"
-        return 1
-    fi
-}
-
-extract ${@+"$@"}
+case "$1" in
+    *.tar.bz2) tar xvjf   "$1" ;;
+    *.tar.gz)  tar xvzf   "$1" ;;
+    *.bz2)     bunzip2    "$1" ;;
+    *.rar)     unrar x    "$1" ;;
+    *.gz)      gunzip     "$1" ;;
+    *.tar)     tar xvf    "$1" ;;
+    *.tbz2)    tar xvjf   "$1" ;;
+    *.tgz)     tar xvzf   "$1" ;;
+    *.zip)     unzip      "$1" ;;
+    *.Z)       uncompress "$1" ;;
+    *.7z)      7z x       "$1" ;;
+    *)
+        echo "$1: oops, cannot be extracted" 1>&2
+        exit 1
+        ;;
+esac
