Update git-ignore

diff --git a/bin/git-ignore b/bin/git-ignore
--- a/bin/git-ignore
+++ b/bin/git-ignore
@@ -8,9 +8,54 @@ if ! is_git_repo; then
     exit 1
 fi
 
-if [ -z "$1" ]; then
-    exit 0
+# status code
+status=0
+# root of ignore file
+root="$(git rev-parse --show-toplevel)"
+
+# check options
+for arg in "${@:-}"
+do
+    case "$arg" in
+        "-l"|"--local")
+            shift
+            root="."
+            ;;
+        -*|--*)
+            echo "$1: unknown option"
+            exit 1
+            ;;
+    esac
+done
+
+ignoref=${root:?not set}/.gitignore
+if [ ! -f "$ignoref" ]; then
+    echo "$ignoref: no such file or directory" 1>&2
+    exit 1
 fi
 
-root="$(git rev-parse --show-toplevel)"
-echo "$@" | tr " " "\n"  >>"${root:-.}"/.gitignore
+# check normal arguments
+for arg in "${@:-}"
+do
+    if [ -z "$arg" ]; then
+        # view
+        cat "$ignoref"
+    else
+        # check for the duplication
+        if grep -Fxq "$arg" "$ignoref"; then
+            echo "already ignored: $arg" 1>&2
+            status=1
+        else
+            echo "$arg" >>"$ignoref"
+            if [ $? -eq 0 ]; then
+                echo "add $arg to $ignoref successfully"
+            else
+                echo "cannot add $arg to $ignoref" 1>&2
+                status=1
+            fi
+        fi
+    fi
+done
+
+# return
+exit $status
