Devide .zshrc and .bashrc into tmuxx and merge

diff --git a/bin/tmuxx b/bin/tmuxx
--- a/bin/tmuxx
+++ b/bin/tmuxx
@@ -1,38 +1,67 @@
 #!/bin/bash
-#
-# @(#) tmuxx v0.1.0 2015-08-05
-#
-# Usage:
-#   tmuxx
-#
-# Description:
-#   attach to an existing tmux session, or create one if none exist
-#   also set up access to the system clipboard from within tmux when possible
-#   e.g.,
-#   https://gist.github.com/1462391
-#   https://github.com/ChrisJohnsen/tmux-MacOSX-pasteboard
-#
-######################################################################
 
-if ! type tmux >/dev/null 2>&1; then
-    echo 'Error: tmux command not found' 1>&2
-    exit 1
-fi
+. "$DOTPATH"/etc/lib/vital.sh
 
-if [ -n "$TMUX" ]; then
-    echo "Error: tmux session has been already attached" 2>&1
-    exit 1
-fi
+# tmux_automatically_attach attachs tmux session automatically
+#tmux_automatically_attach() {
+    is_ssh_running && return 1
 
-if tmux has-session >/dev/null 2>&1 && tmux list-sessions | grep -qE '.*]$'; then
-    # detached session exists
-    tmux attach && echo "$(tmux -V) attached session "
-else
-    if [[ ( $OSTYPE == darwin* ) && ( -x $(which reattach-to-user-namespace 2>/dev/null) ) ]]; then
-        # on OS X force tmux's default command to spawn a shell in the user's namespace
-        tmux_config=$(cat $HOME/.tmux.conf <(echo 'set-option -g default-command "reattach-to-user-namespace -l $SHELL"'))
-        tmux -f <(echo "$tmux_config") new-session && echo "$(tmux -V) created new session supported OS X"
+    if is_screen_or_tmux_running; then
+        if is_tmux_runnning; then
+            if has "cowsay"; then
+                if [[ $(( RANDOM % 5 )) == 1 ]]; then
+                    cowsay -f ghostbusters "G,g,g,ghostbusters!!!"
+                    echo ""
+                fi
+            else
+                echo ' _____ __  __ _   ___  __ '
+                echo '|_   _|  \/  | | | \ \/ / '
+                echo '  | | | |\/| | | | |\  /  '
+                echo '  | | | |  | | |_| |/  \  '
+                echo '  |_| |_|  |_|\___//_/\_\ '
+            fi
+            export DISPLAY="$TMUX"
+        elif is_screen_running; then
+            # For GNU screen
+            :
+        fi
     else
-        tmux new-session && echo "tmux created new session"
+        #if shell_has_started_interactively && ! is_ssh_running; then
+        if ! is_ssh_running; then
+            if ! has "tmux"; then
+                echo "tmux not found" 1>&2
+                return 1
+            fi
+
+            if tmux has-session >/dev/null 2>&1 && tmux list-sessions | grep -qE '.*]$'; then
+                # detached session exists
+                tmux list-sessions | perl -pe 's/(^.*?):/\033[31m$1:\033[m/'
+                echo -n "Tmux: attach? (y/N num/session-name) "
+                read
+                if [[ "$REPLY" =~ ^[Yy]$ ]] || [[ "$REPLY" == '' ]]; then
+                    tmux attach-session
+                    if [ $? -eq 0 ]; then
+                        echo "$(tmux -V) attached session"
+                        return 0
+                    fi
+                elif tmux list-sessions | grep -q "^$REPLY:"; then
+                    tmux attach -t "$REPLY"
+                    if [ $? -eq 0 ]; then
+                        echo "$(tmux -V) attached session"
+                        return 0
+                    fi
+                fi
+            fi
+
+            if is_osx && has "reattach-to-user-namespace"; then
+                # on OS X force tmux's default command
+                # to spawn a shell in the user's namespace
+                tmux_login_shell="/bin/zsh"
+                tmux_config=$(cat ~/.tmux.conf <(echo 'set-option -g default-command "reattach-to-user-namespace -l' $tmux_login_shell'"'))
+                tmux -f <(echo "$tmux_config") new-session && echo "$(tmux -V) created new session supported OS X"
+            else
+                tmux new-session && echo "tmux created new session"
+            fi
+        fi
     fi
-fi
+#}
