Refactoring and change double quote to single

diff --git a/etc/install b/etc/install
--- a/etc/install
+++ b/etc/install
@@ -1,6 +1,7 @@
 #!/bin/bash
 
-trap 'e_error "$0: DANGER: CLOSING..."; exit 1' INT ERR
+# An interrupt (typically ^C) has the effect of aborting the current command
+trap 'e_error "Abort the command that is in progress"; exit 1' INT ERR
 set -e
 set -u
 
@@ -16,8 +17,8 @@ cat <<-'EOT'
  \__,_|\___/ \__|_| |_|_|\___||___/ 
 
 *** WHAT'S INSIDE? ***
-  1. Download https://github.com/b4b4r07/dotfiles
-  2. Symlinking to your home directory
+  1. Download https://github.com/b4b4r07/dotfiles.git
+  2. Symlinking dot files to your home directory
   3. (Optional): Set following some config files within etc/
 
 See the README for documentation.
@@ -30,17 +31,24 @@ EOT
 
 export DOTFILES=~/.dotfiles
 
-# Logging stuff.
+# Insert newline
 function e_newline() { echo -en "\n"; }
+# Normal style of writing
 function e_header()  { echo -e "\n\033[1m$*\033[0m"; }
+# Success
 function e_success() { echo -e " \033[1;32m✔\033[0m  $*"; }
+# Failure
 function e_error()   { echo -e " \033[1;31m✖\033[0m  $*" 1>&2; }
+# Result
 function e_arrow()   { echo -e " \033[1;34m➜\033[0m  $*"; }
+# Check if exists
 function is_exist()  { type "$1" >/dev/null 2>&1; return $?; }
 
 #
 # $ make install
 #
+# This is a make install, which is functionize
+# To execute all sh files within etc/init/.
 function make_install()
 {
     local -i i=1
@@ -50,9 +58,9 @@ function make_install()
     for file in "${files[@]}"; do
         e_header "$i/${#files[@]:-} $(basename $file): running..."
         if bash "$file"; then
-            e_success "DONE."
+            e_success 'done'
         else
-            e_error "ERROR!!"
+            e_error 'error!!'
         fi
         ((i++))
     done
@@ -67,23 +75,23 @@ function dotfiles()
 
             e_header "Updating..."
             make update
-            e_success 'DONE.'
+            e_success 'done'
         elif is_exist 'curl'; then
             #e_header 'Please re-install after executing "make clean"'
             e_arrow "Change to the $DOTFILES directory"
             cd $DOTFILES
 
-            e_arrow "Cleaning dotfiles..."
+            e_arrow 'Cleaning dotfiles...'
             make clean
 
-            e_arrow "Re-installing and deploying..."
+            e_arrow 'Re-installing and deploying...'
             cd /tmp
             curl -fsSL -o dotfiles.zip https://github.com/b4b4r07/dotfiles/archive/master.zip
             unzip -oq dotfiles.zip
             mv dotfiles-master $DOTFILES
             cd $DOTFILES
             make deploy
-            e_success 'DONE.'
+            e_success 'done'
         else
             e_error 'Require: git or curl'
             return 1
@@ -104,12 +112,12 @@ function dotfiles()
             e_error 'Require: git or curl'
             return 1
         fi
-        e_success 'Done'
+        e_success 'done'
 
         cd $DOTFILES
         e_header 'Deploying dotfiles...'
         make deploy
-        e_success 'Done'
+        e_success 'done'
 
         if [[ "${1:-}" == "install" ]]; then
             e_header 'Installing...'
@@ -117,19 +125,24 @@ function dotfiles()
             make_install
         fi
 
-        # Restart shell
-        # not restart:
-        #   curl -fsSL {URL} | bash
-        if [ ! -p /dev/stdout ]; then
-            e_newline
-            e_arrow "Restart your shell"
+        #
+        e_newline
+        if [ -p /dev/stdout ]; then
+            e_arrow 'Restart your shell, manually'
+        else
+            # Restart shell if specified "bash -c $(curl -L {URL})"
+            # not restart:
+            #   curl -L {URL} | bash
+            e_arrow 'Restart your shell'
             exec "${SHELL:-/bin/zsh}"
         fi
     fi
 }
 
+# Main
 #
-# ~~~ MAIN PART ~~~
+# Check if run from a command line
+# python-like "if __name__ == '__main__':"
 #
 # A SAFETY system
 # Note: This script is designed to be run from a command line shell.
@@ -140,7 +153,7 @@ if [[ "$0" =~ $(basename "${BASH_SOURCE:-}") ]]; then
     e_newline
 
     # Push off the safety catch
-    if [[ "${1:-}" != "directly" ]]; then
+    if [[ "${1:-}" != 'directly' ]]; then
         exit 1
     fi
 fi
