Add snippet for gcp context switch

diff --git a/.config/afx/local.yaml b/.config/afx/local.yaml
--- a/.config/afx/local.yaml
+++ b/.config/afx/local.yaml
@@ -7,6 +7,15 @@ local:
       [[ $SHELL == *zsh* ]]
     sources:
     - '[0-9]*.zsh'
+    snippet: |
+      function gcp() {
+        type fzf &>/dev/null || { echo "fzf not found"; return 1; }
+        local project=$(gcloud projects list ${1+--filter ${1}} | grep -v sys- | fzf --height 50% --header-lines=1 --reverse --multi --cycle --exit-0 | awk '{print $1}')
+        if [[ -z ${project} ]]; then
+          return 0
+        fi
+        gcloud config set project "${project}"
+      }
   depends-on:
   - google-cloud-sdk
 
